Task 1

Create a one dimensional random numpy array of size 10.

In [ ]:
import numpy as np

random_array = np.random.rand(10)

print(random_array)

[0.7278781  0.61559324 0.85628375 0.72371607 0.80858646 0.45854868
 0.85165549 0.25733269 0.48112771 0.82995508]


Task 2

Create a two dimensional numpy array of size 7x6 and reshape it to 3x14 array.

In [ ]:


# Create a 7x6 array
original_array = np.arange(42).reshape(7, 6)

print("Original Array (7x6):")
print(original_array)
print()

# Reshape to a 3x14 array
reshaped_array = original_array.reshape(3, 14)

print("Reshaped Array (3x14):")
print(reshaped_array)

Original Array (7x6):
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]
 [36 37 38 39 40 41]]

Reshaped Array (3x14):
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20 21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34 35 36 37 38 39 40 41]]


Task 3

Create an array and extract all the odd numbers from it. [array([0,1,2,3,4,5,6,7,8,9])].

In [ ]:


array_1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Extract odd numbers
odd_numbers = array_1[array_1 % 2 != 0]

print("Array_1:", array_1)
print("Odd Numbers:", odd_numbers)

Array_1: [0 1 2 3 4 5 6 7 8 9]
Odd Numbers: [1 3 5 7 9]


Task 4

Replace all the odd numbers in the previous array with -1.
==> array([ 0, -1, 2, -1, 4, -1, 6, -1, 8, -1])

In [ ]:


array_1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])




# Replace odd numbers with -1
array_1 = np.where(array_1 % 2 != 0, -1, array_1)

print("Array_1:", array_1)

Array_1: [ 0 -1  2 -1  4 -1  6 -1  8 -1]


Task 5

Replace all the odd numbers in the previous array with -1 without affecting the original
array.
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
out
> array([ 0, -1, 2, -1, 4, -1, 6, -1, 8, -1])
arr
> array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:


array_1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Replace odd numbers with -1
modified_array = np.where(array_1 % 2 != 0, -1, array_1)

print("Array_1:", array_1)
print("Modified Array:", modified_array)

Array_1: [0 1 2 3 4 5 6 7 8 9]
Modified Array: [ 0 -1  2 -1  4 -1  6 -1  8 -1]


Task 6

Get the positions where elements of a and b match
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [ ]:


a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

matching_positions = np.where(a == b)

print("Matching Positions:", matching_positions)

Matching Positions: (array([1, 3, 5, 7]),)


Task 7

Get all the items between 5 and 10 from a.
a = np.array([2, 6, 1, 9, 10, 3, 27])

In [ ]:


a = np.array([2, 6, 1, 9, 10, 3, 27])

items = a[(a >= 5) & (a <= 10)]

print("Items between 5 and 10:", items)

Items between 5 and 10: [ 6  9 10]


Task 8

Create a vector of size 10 with zeros. Then create a vector of size 10 with ones. Change
their dimension and after that merge the the two vector vertically and horizontally using
“concatenate”.

In [ ]:


# Create a vector of size 10 with zero
zero_vector = np.zeros(10)

# Create a vector of size 10 with ones
one_vector = np.ones(10)

# Reshape the vectors to have 10 rows and 1 column
zero_vector = zero_vector.reshape(10, 1)
one_vector = one_vector.reshape(10, 1)

# Vertically concatenate the vectors
vertical_concatenated = np.concatenate((zero_vector, one_vector), axis=0)

# Horizontally concatenate the vectors
horizontal_concatenated = np.concatenate((zero_vector, one_vector), axis=1)

print("Zeros Vector:")
print(zero_vector)

print("\nOnes Vector:")
print(one_vector)

print("\nVertically Concatenated:")
print(vertical_concatenated)

print("\nHorizontally Concatenated:")
print(horizontal_concatenated)

Zeros Vector:
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]

Ones Vector:
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]

Vertically Concatenated:
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]

Horizontally Concatenated:
[[0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]]


Task 9

Create an ndarray x of shape= (5, 4) with random numbers – Each of the 5 rows represents
a sample with 4 features

In [ ]:
# np.random.seed(0)

# Create a 5x4 ndarray with random numbers
x = np.random.rand(5, 4)

print(x)



[[4.20100479e-01 6.86345101e-02 2.95890034e-01 7.79347913e-01]
 [8.19046705e-02 9.26604446e-01 8.60806131e-01 3.42602203e-01]
 [4.78425694e-01 6.69895667e-01 9.78978121e-01 5.86896261e-01]
 [4.04958008e-02 7.12237392e-01 5.58481751e-01 9.24266182e-01]
 [5.26869106e-03 3.38772112e-02 2.46753393e-04 3.24673105e-01]]


Task 10

Create a flat ndarray y of shape=(5, ), whose elements are 0 and 1 – Each element
is the class label of the corresponding sample in x [Hint: use np.random.rand(...) and
np.random.randint(...)]
import numpy as np
n_samples = 5
n_features = 4
x = np.random.rand(n_samples, n_features)
y = np.random.randint(0, 2, n_samples)
print ’x =’, x
print ’y =’, y

In [ ]:


n_samples = 5
n_features = 4

#x = np.random.rand(n_samples, n_features)
y = np.random.randint(0, 2, n_samples)

#print('x =', x)
print('y =', y)

y = [1 0 0 0 0]


Task 11

Define a function extract_subset(x, y, y0) that takes as input: – the feature matrix x, and
the labels y from the previous exercise – a target class y0 (i.e., either y0=0 or y0=1) and
returns a feature matrix containing only samples belonging to y0

In [ ]:


def extract_subset(x, y, y0):
    subset_x = x[y == y0]
    return subset_x

y0 = 1

subset_x = extract_subset(x, y, y0)

print("Original x:")
print(x)

print("\nSubset x for target class", y0, ":")
print(subset_x)



Original x:
[[0.28834358 0.55246414 0.04583097 0.22269079]
 [0.97631947 0.75117368 0.23346312 0.16310892]
 [0.14665779 0.09670735 0.9024229  0.73541995]
 [0.10277587 0.22512866 0.27296103 0.59379828]
 [0.16537309 0.52751809 0.83663681 0.7516464 ]]

Subset x for target class 1 :
[[0.28834358 0.55246414 0.04583097 0.22269079]]


Task 12

Import a dataset (IRIS dataset) by keeping the text and numbers intact.

In [ ]:
from sklearn.datasets import load_iris

# Load the IRIS dataset
iris = load_iris()
print(iris.data)
print(iris.target)

# Access the data
data = iris.data
target = iris.target

# Print the description of the dataset
print(iris.DESCR)

# Print the feature names
print("Feature Names:", iris.feature_names)

# Print the target names
print("Target Names:", iris.target_names)

# Print the first few samples
print("Data Samples:")
for i in range(5):
    print("Sample {}: Features: {}, Target: {}".format(i + 1, data[i], target[i]))


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

Task 13

Find the mean, median and standard deviation of the 1st column of the given dataset.
Give statistical summary of the dataset as many as possible.

In [ ]:
import numpy as np
from sklearn.datasets import load_iris

# Load the IRIS dataset
iris = load_iris()

# Access the data
data = iris.data

# Extract the 1st column
first_column = data[:, 0]

# Calculate mean, median, and standard deviation
mean = np.mean(first_column)
median = np.median(first_column)
std_dev = np.std(first_column)

print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)




Mean: 5.843333333333334
Median: 5.8
Standard Deviation: 0.8253012917851409
